apiVersion: apps/v1
kind: Deployment
metadata:
  name: newspringapp-deployment
  labels:
    app: newspringapp-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: newspringapp-deployment
  template:
    metadata:
      labels:
        app: newspringapp-deployment
    spec:
      containers:
        - name: newspringapp-deployment
          image: public.ecr.aws/d7p5a0c0/k8s:deploy:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

